// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vnhcihkdswfvmuhpsiyk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZuaGNpaGtkc3dmdm11aHBzaXlrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkwNzU2ODMsImV4cCI6MjA3NDY1MTY4M30.pPJZ-H2NaGAqlk8CqsN499Ny-gJzo_xt9Lhz87_Ot4I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});